### ISSUE TITLE
MMOItems support doesn't work

### ISSUE THREAD

**Issue by MidnightSugar** [divios/DailyShop#101]
Here is my item. 
Just says material is required for item.

```items:
  MMOITEM:
    mmoItem:
      - type: SWORD
      - id: COMBAT_STAVE
    buyPrice:
      min: '20'
      max: '50'
    stock:
       type: GLOBAL
       amount: 5
    rarity: Common
    econ:
      name: vault
    confirm_gui: true

**Comment by divios** [comment]
Hi! I just checked and the wiki documentation was outdated, sorry about that. I just updated it with the right format, here is the [shortcut](https://github.com/divios/DailyShop/wiki/mmoitems)
