### ISSUE TITLE
Add support for ItemsAdder

### ISSUE THREAD

**Issue by CycTaker** [divios/DailyShop#104]
Hi i am looking for a store plugin and i saw your plugin that can have custom items and staff but you only support Oraxen. Can you add support for itemsadder to because i cant find another shop plugin that can support itemsadder custom items?

**Comment by divios** [comment]
Hi! Yeah sure, I will check the plug-in api and if it is possible, I will add direct support, but it should be no problem

**Comment by CycTaker** [comment]
Thank you so much :)

**Comment by Adri417** [comment]
Good morning !
I still hesitate to buy the plugin.
I also need ItemsAdder support.
Do you have a discord?
Maybe that will convince me to buy it for simpler support and more effective communication

**Comment by divios** [comment]
The new update implements this!
