### ISSUE TITLE
Support for custom gui

### ISSUE THREAD

**Issue by CycTaker** [divios/DailyShop#109]
Hi thank you so much for adding support for itemsadder but can you add for custom guis like this one?
![Capture](https://user-images.githubusercontent.com/65673341/154670541-513ba629-6110-4607-bf05-82c38ede3394.PNG)

**Comment by Akiranya** [comment]
I guess you can achieve it by simply changing the title of GUI (see this guide: https://itemsadder.devs.beer/plugin-usage/advanced/guis). There is really no need of coding on dailyshop side :3

**Comment by divios** [comment]
Sorry for the late reply, thanks @Akiranya for the input. I can affirm this since others users have same with me screen with custom guis

**Comment by John-tf** [comment]
@divios i dont understand. Can i use custom guis?

**Comment by divios** [comment]
> @divios i dont understand. Can i use custom guis?

As far as I know yes, if you follow [this](https://itemsadder.devs.beer/plugin-usage/advanced/guis) tutorial you should be able to do it

**Comment by John-tf** [comment]
it works
