### ISSUE TITLE
Start at zero items in selection GUI

### ISSUE THREAD

**Issue by MidnightSugar** [divios/DailyShop#110]
It weird how when I am purchasing it always starts at one item. This is really odd behavior, it causes confusion, and messes up the GUI since people are encouraged to buy stacks + 1, which is weird. Like if I want to buy a stack of logs, I'll usually end up buying a stack plus an extra one because I don't want to click REMOVE 1.

**Comment by divios** [comment]
Mmm yeah I guess you have a point in that, never thought of it that way, I’ll try myself and if I find it better I will implement it

**Comment by divios** [comment]
The new update implement this! :D
