### ISSUE TITLE
Default configs not working

### ISSUE THREAD

**Issue by xNikees911** [divios/DailyShop#111]
Hi, I bought your DailyShop Premium plugin and I want to use it but when I have default files I have a lot of errors.
![image](https://user-images.githubusercontent.com/89745544/154765252-5d81a70d-99f5-4110-bf88-c2000b231c58.png)

Also please tell me why your plugin wiki it's not good to read, I can't understand how this plugin works because yours wiki it's terrible.

Please tell me how to do this thing from spigot descriptions of your plugin like random pool of items.
**DailyShop aims to fix the still present problems in both methods by introducing shops with random items, picked from a configurable pool of items which are replaced by new random items after a certain amount of time.**

**Comment by divios** [comment]
Hi! I’m not sure what you mean by defaults config, could you elaborate? 

Also I’m working on the error you are receiving, but it has nothing to do with the defaults config

it really pains me to hear your thoughts about the wiki… I will try to update it explaining better the plug-ins functionality, but the “random pools of item” is the code feature of the plugin, you add items to a shop, and after a certain period of time, the shop restocks with new items ( from the items you added before).

if you have more questions don’t hesitate to ask

**Comment by xNikees911** [comment]
What I mean about default configs?
I mean when I restart server and your plugin make new defaults files and I want to check it so I use /rdshop open command then I got all of this error above.

**Comment by xNikees911** [comment]
Maybe you can help me step by step how to do that because from your wiki I can't understand how to do that.
I want to make this random pool of items. Can you introduce how to make it step by step please? (I think your wiki don't have information about it or I don't know where is it)

**Comment by divios** [comment]
Hi! Sorry for the late reply. Please use the new verion, it the error you pointed before and also the placeholders not working.

**Comment by divios** [comment]
Yes, of course i can guide you:

1. If you want to import your items from shopGui+, then please check [this](https://github.com/divios/DailyShop/wiki/ShopGui). 
2. For the random pool of items, after you have imported your shopGui+ items, you can check the items the shop has with **/ds manager** and selecting the shop where you import them. All the items showed there are the items that will be picked randomly on each restock and will be available for the players ( this is the main idea of the plugin).

**Comment by xNikees911** [comment]
**For the random pool of items, after you have imported your shopGui+ items, you can check the items the shop has with /ds manager and selecting the shop where you import them. All the items showed there are the items that will be picked randomly on each restock and will be available for the players ( this is the main idea of the plugin).**

Okey, but is it possible to set up 5 items per day from 200 items in whole pool?

**Comment by divios** [comment]
Yes of course, although is not exactly straight forward. On the /ds manager, if you **shift click** the shop you will see the display/inventory of the shop. The shop restock works like this: it randomly picks the items in the pool and insert them in the first empty slot of the shop inventory until there are no more items in the pool or no more empty slots. 

Knowing this, you can set up 5 items per day from 200 items if you only leave 5 empty slots in the shop view/inventory. You can also set AIR items, which is better explained [here](https://github.com/divios/DailyShop/wiki/static-items)
