### ISSUE TITLE
Not save in config

### ISSUE THREAD

**Issue by mani1232** [divios/DailyShop#112]
![image](https://user-images.githubusercontent.com/70480001/154821289-ba4f7baa-b4c1-4ff0-bd14-31651d85367a.png)
![image](https://user-images.githubusercontent.com/70480001/154821304-2257862c-bb75-474d-89a4-d54d7c80768f.png)

**Comment by divios** [comment]
Hi! Sometimes depending on the text visualizer you need to close/open the file to see the changes, could you double check if this is the case?

**Comment by Akiranya** [comment]
In my case , the in-game changes instantly reflect on the file :3 maybe just double check the file editor ? (btw I'm using VSCode)

**Comment by divios** [comment]
Yes, VSCode refresh automatically, but other code editors don't have that behavior, at least by default. He is using notepad+, I'm almost certain it does not refresh the file automatically

**Comment by divios** [comment]
You are right, there was a bug that is causing this, It will be fixed on the next update

**Comment by divios** [comment]
The new version should fix this
