### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by yellow-pillow** [divios/DailyShop#117]
Hi, could you please add a change button function for buying and selling?

now the left mouse button to buy and the right button to sell

make the change in the settings))

(I do not need to buy items on the server and so I would like what would be a more intuitive interface ( today I bought a premium version)

preferably separately in the settings of each store

**Comment by yellow-pillow** [comment]
and when will there be a reduction in price, which will depend on how many people have sold goods of the same type in a day?

**Comment by divios** [comment]
Hi! Yeah your suggestion has a point, I will implement this on the next update. And for the price changing depending on the supply/demand, is something a really want to do, but right now the priority I have is reformat the code,  make it more robust and easier to maintain, so for the next weeks there won't be new features (at least big ones)

**Comment by divios** [comment]
The new update finally implements this, check [here](https://github.com/divios/DailyShop/wiki/Override-click-actions) to see how
