### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by xNikees911** [divios/DailyShop#118]
Hi, I have suggestion to your plugin. In priceModifiers.yml I can set up any price modifier, but maybe you can make random price modifier? Example from file:
**modifiers:
  example1:
    scope: GLOBAL
    type: BUY
    value-min: -0.5
    value-max: -0.75**
And this price modifier will be completely random for the global buy price (same for the sell price). Do you want to add it? (quick update - need on my server but I don't insist)

**Comment by xNikees911** [comment]
You was looking on it? Is it possible to add it?

**Comment by divios** [comment]
hI! Yeah I think is possible, but I have other priorities in mind right now (fixing some bugs). As soon as I'm settle with that, I will implement this

**Comment by xNikees911** [comment]
Any estimated time for add it? I want to add it on my server, but I need only this one feature for work it perfectly!

**Comment by xNikees911** [comment]
Hi, is there any progress? There has been a terrible silence here lately :D

**Comment by divios** [comment]
Implemented on the last commit, it will be available on the next update
