### ISSUE TITLE
prices 0_0

### ISSUE THREAD

**Issue by yellow-pillow** [divios/DailyShop#120]
Damn, the old versions were more stable -__-

just watch https://drive.google.com/file/d/13NAvIFNUmqinwclqFVoUZ1BD-Qg1lg2P/view?usp=sharing

**Comment by divios** [comment]
Mmm okay I think I know where the error is, is a minor thing, I will send you the jar fixing It tomorrow

**Comment by yellow-pillow** [comment]
oooh shit, I couldn't install the old version of the plugin it doesn't read the files correctly...

**Comment by yellow-pillow** [comment]
Panic over, I found my grandfather's backup))

**Comment by divios** [comment]
[Here it is](https://we.tl/t-SPpnUzVM3E). It was a very small bug, I was passing the wrong variable to a function

**Comment by yellow-pillow** [comment]
By the way, I forgot to say! For some reason when you click the wrong mouse button you get thrown out of the store, it can be seen in the same video at the beginning
