### ISSUE TITLE
weird close

### ISSUE THREAD

**Issue by yellow-pillow** [divios/DailyShop#121]
By the way, I forgot to say! For some reason when you click the wrong mouse button you get thrown out of the store, it can be seen in the same video at the beginning

its for this https://github.com/divios/DailyShop/issues/120

**Comment by divios** [comment]
Yeah this is how is managed now, if there is a problem the shop will be closed

**Comment by yellow-pillow** [comment]
but this is inconvenient in theory, you need to repeat all the steps again

**Comment by divios** [comment]
Fixed with [this commit](https://github.com/divios/DailyShop/commit/6b9e58529d042aacec806ff7727e972cf36b4150). The next update will implement it
