### ISSUE TITLE
Allow us to change the word "Vault".

### ISSUE THREAD

**Issue by Zangerine** [divios/DailyShop#123]
Honestly the fact that it says "You sold x of item for 999.99 Vault" is pretty annoying. It would be great if we could change this or even remove the word entirely. If vault is being used it would be good if we could use the $ sign before the amount it sold/bought for.

**Comment by divios** [comment]
Hi! You can already do that [with this](https://github.com/divios/DailyShop/wiki/Changing-currency-names).

In your particular case:

Econ-names:
   Vault: "$"

**Comment by divios** [comment]
Also you can edit the entire message on `lang.yml`, under `lang.messages.buy_item and change it as you see fit.`

**Comment by Zangerine** [comment]
Ahh I looked but obviously not hard enough. Sorry! Thank you for letting me know I really appreciate the fast response :)
