### ISSUE TITLE
More Rarities

### ISSUE THREAD

**Issue by MidnightSugar** [divios/DailyShop#126]
Rarity stops at 5% and it would be better to have rarities that go lower than this, like 1% or even 0.1%.

**Comment by MidnightSugar** [comment]
Better yet, wouldn't it be easier to just set the rarity percentage instead of just using preset rarities?

**Comment by divios** [comment]
Hi! Yeah this is something I have in mind, there should be a rarities.yml where you could edit the rarities available to your liking.

**Comment by divios** [comment]
Implemented on the last commit, it will be available on the next update
