### ISSUE TITLE
Translatable rarity

### ISSUE THREAD

**Issue by YKDZ** [divios/DailyShop#127]
I am a Chinese user of DailySop. When I translate plugin to Chinese, I have notified that I can not translate rarity in lang.yml(Common 
 Rare etc).
I have also realized that some other string that can not be translated , for example, the  Plugin Reloaded title message.
I think you can add the rarity to the lang file, make it easy for plugins to be translated into more languages.

By the way, can I give you the translation to have it built into the plugin jar?

**Comment by divios** [comment]
Hi! With the implementation of #126, you should be able to translate rarities as you see fit (not only that, also percentages, colors, etc...). I will also add the string that are not translatable to the lang.yml


I close this issue since is the same as 126
