### ISSUE TITLE
Chinese name garbled problem

### ISSUE THREAD

**Issue by YKDZ** [divios/DailyShop#128]
I noticed a problem: the product names in the buy and sell message are always in English. I have to manually set the name: "XXX" for the items to change the product name to Chinese.
But when I set the name to any Chinese, it will become garbled after reloading the plugin.

**Comment by divios** [comment]
I see, this must have something to do with the encoding, I will check if it can be fixed

**Comment by divios** [comment]
Also I could add support for automatic translations

**Comment by divios** [comment]
Hi! The new update displays the name correctly according to the client's language, so you don't have to replace the names manually
