### ISSUE TITLE
I can't buy because "I don't have permissions" but I have all the permissions

### ISSUE THREAD

**Issue by yosoyluc** [divios/DailyShop#130]
![image](https://user-images.githubusercontent.com/80115136/160195623-4521bc42-57d8-4dae-89f7-c25609ac7fb1.png)

**Comment by divios** [comment]
Hi! What permissions did you give to the player?

**Comment by divios** [comment]
Closed due to inactivity

**Comment by yosoyluc** [comment]
> Hi! What permissions did you give to the player?

It's a test with owner rank, owner rank have "*" permission
