### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by MidnightSugar** [divios/DailyShop#132]
I get about 70k lines of console spam every time I start up server, caused by dailyshop. Please fix.
Spams "at com.google.gson.internal.bind.TypeAdapters$27.write(TypeAdapters.java:721)"
Full startup log is too large for pastebin: https://www.mediafire.com/file/dr6g9hc91n3oxzv/latest.log/file

**Comment by divios** [comment]
Hi! Sorry for the late reply. Yeah, it seems there is an error when the shops are saved that is causing this. Could you send me your dailyshop folder? Is the only way to reproduce the error

**Comment by MidnightSugar** [comment]
https://www.mediafire.com/file/iknd75cv4jhhnjz/DailyShop.zip/file

**Comment by divios** [comment]
This is likely caused by a circle reference... I'm investigating it, but the error is thrown from a parallel thread, so it should not impact the server performance

**Comment by divios** [comment]
Hi! I just found the cause. I was passing a variable by mistake that caused a circle reference... Here is [the build ](https://we.tl/t-POPtwb4SOP) that fix it
