### ISSUE TITLE
Can't disable option allowSellOnMax: false

### ISSUE THREAD

**Issue by MidnightSugar** [divios/DailyShop#138]
I am trying to remove "allowSellOnMax: false" on items, but I am unable to, the configs just put back to false no matter what I do. I tried changing it while server is on and off and it just puts it back to false every time. I also tried deleting the config option, but it also puts the line right back.

**Comment by MidnightSugar** [comment]
This is preventing people from using the sell feature of the plugin.

**Comment by divios** [comment]
Hi! If you remove it then the plugin by default set it to false, try setting the allowSellOnMax to true, that should work

**Comment by MidnightSugar** [comment]
That is the first thing I tried. It doesn't work. I set it to true, but it puts to false as soon as I reload the plugin or restart the server.

**Comment by divios** [comment]
Shoot, you were right, I forgot to add a condition that made it work, [this build fix ](https://we.tl/t-03J99bkuo8)it!

Thanks for reporting it!
