### ISSUE TITLE
Shopkeeper balance feature broken

### ISSUE THREAD

**Issue by MidnightSugar** [divios/DailyShop#141]
The shopkeeper balance is broken:

Initial ShopKeeper Balance: 461.29
Sold Enchanted Book with Frost Walker 2 for 56.74
New Shop Balance: 460.29 (Also the item stock did not go up like it should)
Bought Enchanted Book with Feather Falling IV for 192.20
New Shop Balance: 461.29

Tested on latest version on spigot (3.8)

**Comment by landrace877** [comment]
I have the exact same problem.
Only the number of items purchased and sold has increased, and the correct increase / decrease has not been made.

**Comment by divios** [comment]
Hi! This was fixed on the last update
