### ISSUE TITLE
Pointless server spam bug. DailyShop-3.8B (premium)

### ISSUE THREAD

**Issue by Mat95** [divios/DailyShop#144]
Clicking in your own inventory while in a shop menu causes this server bug for i assume no reason at all?
Super annoying as it spams the console with many players doing this at random.
Spigot-1.18.2
![66b0ecc5890d4202913babfc659401d5](https://user-images.githubusercontent.com/11804912/167282637-8c1fa43e-52b0-4d15-b6da-995ec7a30cf5.png)

**Comment by divios** [comment]
Hi! You are right, [this build](https://we.tl/t-oW01thvMTU) would fix it.
