### ISSUE TITLE
Unsure if this is a bug or intended. Annoying...

### ISSUE THREAD

**Issue by Mat95** [divios/DailyShop#146]
Why does everyone in game get spammed with Renovated messages each time shops restock? Shouldnt this be an admin permission and not something visible to everyone? If not why have all that random text in front of the custom lang.yml text of "Renovated items of shop menu"?

![87f840583a212d61f1dc51e13e03492d](https://user-images.githubusercontent.com/11804912/168282258-58d77633-639b-42a3-8061-3ed3b1e08763.png)

**Comment by Mat95** [comment]
> Issue not fully resolved <

Some bloke on spigot helped me with part of this issue do this:
LEFT: BUY
RIGHT: SELL
announce_restock: false

Apparently version 3.8B broke the "DailyShop" part of messages throughtout the entire plugin. Selling/Buying/Restocking and anything else.

Running Version 3.8 shows what it should look like.
![1531c22c9469d1a28b27ca1093706701](https://user-images.githubusercontent.com/11804912/168399813-fa9231bb-a8c1-498c-9910-f083f0b08a92.png)

Sadly using an older version, You have to deal with this >
![bebf03dcf2b5fee4dfa1d0a1483e0a41](https://user-images.githubusercontent.com/11804912/168400019-e2338ab3-3785-4852-9734-fa0e20c5c5ee.png)

So one bug was fixed, But you introduced a new bug. I guess i will deal with it until its re-fixed.

Suggestion > Let us edit the "DailyShop" text part of every message that shows up.
Us premium users shouldn't have to deal with free advertisement if we don't want that text being there at all?
I just want it to be displayed as "&6&lSHOP &8> &7(whatever message in lang.yml)
Keep that in the free version please?

**Comment by divios** [comment]
Hi!

Yeah by default when a shop is restock it is announced, so players know when new items are available. You can override this "announce_restock: false" as you did

Also the weird text, as you also realize, is a problem with the gradient feature (im working on it)

Looking into the /ds sell exception too

**Comment by divios** [comment]
Hi! [This build](https://we.tl/t-oW01thvMTU) should fix it.
