### ISSUE TITLE
DB Error DailyShop-3.8B (premium)

### ISSUE THREAD

**Issue by TheMalasti** [divios/DailyShop#147]
![Снимок экрана 2022-05-15 043720](https://user-images.githubusercontent.com/67843844/168453615-09324440-a8d5-423b-b862-d428fcfb0a15.png)

**Comment by TheMalasti** [comment]
No, i had bought your premium plugin and placed it without free version

**Comment by TheMalasti** [comment]
Give your discord or make a discord channel for your plugin

**Comment by divios** [comment]
Mmm okay thats weird, for now just delete the dailyshop.db file and let it regenerate itself, it will fix it.

I will check what might have caused this

**Comment by TheMalasti** [comment]
It regeretated and it still gives errors and warns

**Comment by TheMalasti** [comment]
Please do not close the ticket if i did not sad that the problem was solved, your plugin is not free!
