### ISSUE TITLE
Support Mod items.

### ISSUE THREAD

**Issue by 849025143** [divios/DailyShop#148]
"Mod items" will not be saved to xxx.yml
pls fix it.

**Comment by divios** [comment]
Hi! What plugin are you using to generate the mod items?

**Comment by 849025143** [comment]
> 你好！你用什么插件来生成模组物品？

DailyShop buy

**Comment by 849025143** [comment]
Premium

**Comment by 849025143** [comment]
mod items = /gamemode 1
