### ISSUE TITLE
download latest version

### ISSUE THREAD

**Issue by Zarkness** [divios/DailyShop#149]
Hi, I tried to compile the plugin to have the latest version and test it and I couldn't, it gave me an error.

**Comment by Zarkness** [comment]
Where can I download the latest version?

**Comment by Zarkness** [comment]
@divios

**Comment by divios** [comment]
Hi! As the README says is open source but you cannot compile the plugin. Nevertheless i want to change this since I dont have time to update the plugin as i used to do, I will ping you when it is ready

**Comment by Zarkness** [comment]
ok, thank you very much and when do you think it would be possible to compile it? @divios
