### ISSUE TITLE
DB Error DailyShop-3.8B (premium) SECOND VERSION

### ISSUE THREAD

**Issue by TheMalasti** [divios/DailyShop#150]
![168453615-09324440-a8d5-423b-b862-d428fcfb0a15](https://user-images.githubusercontent.com/67843844/170438536-6702e587-e146-458f-9e93-a7225564847f.png)
![Снимок экрана 2022-05-26 102107](https://user-images.githubusercontent.com/67843844/170438583-7fe4d608-69db-42ec-9b63-b2aa8a84c94e.png)

**Comment by divios** [comment]
I was going to reply to the other comment, sorry for closing it. 

Please send me your shop files so i can replicate the error

**Comment by TheMalasti** [comment]
[DailyShop.zip](https://github.com/divios/DailyShop/files/8781660/DailyShop.zip)

**Comment by divios** [comment]
Thanks! Since I have two important exams around the corner I may take some days, but I will ping as soon as I fixed it

**Comment by TheMalasti** [comment]
Thank you, we will wait, wish you success the exam

**Comment by divios** [comment]
Hi again! I just finished my exams. I just tried your files in my pc and is working fine. What Minecraft version are you using?

**Comment by TheMalasti** [comment]
Im using paper 1.15.2, right now we are jumping to paper 1.16.5, aftertertommorow i can check your plugin on paper 1.16.5/1.17.1

**Comment by divios** [comment]
Okey, let me know. It seems somehow the shop table on the database is not created before items are being saved, giving the error that the table does not exist. 

It should't be possible unless is another thing, but it is probable that the Minecraft version has something to do with it.

Well let me know if it works on 1.16.5/1.17.1 or not and see if we can narrow what is causing this

**Comment by TheMalasti** [comment]
Today will check your plugin

**Comment by TheMalasti** [comment]
Seems to in 1.16.5 everething works. Thank you

**Comment by TheMalasti** [comment]
Is it posiible to add different types of shop showing like in DeluxeMenus inventory_type: HOPPER?

**Comment by divios** [comment]
> Seems to in 1.16.5 everething works. Thank you

Mmm okay… we’ll I’m glad it is working now, I’ll check that version to see what the error was

**Comment by divios** [comment]
> Is it posiible to add different types of shop showing like in DeluxeMenus inventory_type: HOPPER?
I’m afraid it is not possible right now… and currently I prefer to point all my time to fix bugs and make the plug-in overall more reliable
