### ISSUE TITLE
Time format past 24 hours

### ISSUE THREAD

**Issue by CrypticBlades** [divios/DailyShop#155]
Setting a shop timer past 24 hours does not cause the timer to increase. Furthermore, after testing the options provided in the apidocs of the class DateTimeFormat, I understand that 'H' code only displays values from 0 to 23, so stacking many hours is not an option. 

The next option is to try to find how to utilize the day format options, but there are no options that provide a correct usage of the day format that works for a counter. This is because the day options like "day of year", and "day of month" start at the value of 1 instead of 0, unlike the hour format which can also display values of 0. This means that the number of days displayed would be one more than the actual value, and so anything less than 24 hours would still display 1 for the days. Maybe the class was not optimized to be used as a countdown timer.

So far, I've worked around this problem by utilizing  "day of week, code E" which displays the day on which the timer would end, in an attempt to send an accurate description to the players. 
EX: "HH:mm:ss 'on' EEEE" which can translate to "00:56:49 on Wednesday".
Although, doing this way is still awkward since the numbers are the countdown and the name of the day is the day of the reset. So I still recommend on it being fixed.

A possible solution is if you could find a way to subtract the value by 1 before having it displayed. Another suggestion is to have an option to display the time and date when the shop resets instead of the countdown. If you believe this is a problem worth solving, feel free to come up with your own ideas.

**Comment by divios** [comment]
Hi!

This is very convenient since I was refactoring the database and I just released this problem. I'm working around it. Thanks for reporting it by the way!

**Comment by divios** [comment]
Hi again!

Please try `[this build ](https://we.tl/t-QmMoRxUO6C)`and let me know if everything works as expected. It solves the problem with the timer above 1 day and also introduces a new database optimized database structure

**Comment by CrypticBlades** [comment]
I will try this and get back to you, thank you!

**Comment by CrypticBlades** [comment]
After testing, I have a few things to note:


I would suggest to change the "Days: 3" into "3 Days". I believe this would help placeholder users to combine the placeholder with their own phrases more naturally. For example: "Time left: 3 Days" or "Time until shop reset: 3 Days".

I also ran into an issue with the format being unable to change if the the timer is set to more than one day. I tried 1 Day and 10 seconds (or 86410 seconds), waited for about a minute, and the timer did not change into the HH:mm:ss format. The placeholder continued to stay at "Days: 1". Even after a reload it displays the same. I also tried this with switching between the amount of days by setting the timer to 5 seconds above 2 days (172805 seconds) and it also fails to change from "Days: 2" to "Days: 1". Any timer set to 24 hours or less still works as intended.

And as far as the database is concerned, I am inexperienced with databases so I am unable to provide feedback on that for the moment.

**Comment by divios** [comment]
Thanks for the feedback!! 

Alright I think I forgot to substrate the current time in a condition and that’s why it is not changing, I will fix this as soon as I get from work and I will let you know

**Comment by divios** [comment]
Hi! Try [this build](https://we.tl/t-xFIRjF2SD5), it should finally fix the timer format past 24h, but let me know if everything work fine just in case

**Comment by CrypticBlades** [comment]
Thank you, I have no more other requests to make at the moment. Just for clarification, is the format option you are referring to about adding the day counter to the format as well? You can close this issue after this.

**Comment by divios** [comment]
I was referring to adding an option on the config,yml, for example "# Days, HH:mm:ss" like you said, so you can edit the format.

I will close this issue now but if you still have questions you can still use this ticket
