### ISSUE TITLE
Error when saving 1.19 items

### ISSUE THREAD

**Issue by JShin39** [divios/DailyShop#157]
When adding 1.19 items to the shop, the shop fails to save the items
![Screenshot_4](https://user-images.githubusercontent.com/36411026/175961677-a415a2fe-52ff-4745-908a-b678cb4d239d.png)
.

**Comment by divios** [comment]
Hi! Please try [this build](https://we.tl/t-QmMoRxUO6C) instead. I changed how the database works and it should fix this, and if the error persists it should print the whole error on the console so we can understand what is going on

**Comment by JShin39** [comment]
It works now! Thanks :)

**Comment by JustKira** [comment]
Where can i get this build version
