### ISSUE TITLE
Change ds sell interface ?

### ISSUE THREAD

**Issue by Weyl1** [divios/DailyShop#161]
Good evening, would it be possible to modify the menu interface in lang.yml ?
![changelang](https://user-images.githubusercontent.com/96068728/177057661-9480b0f9-f8f5-4016-b479-d0d06f2a542e.PNG)

**Comment by divios** [comment]
Hi! Yeah, thanks for pointing this out, I will fix it on the next update

**Comment by divios** [comment]
Implemented on the new update
