### ISSUE TITLE
Support /ds sell gui [shopName]

### ISSUE THREAD

**Issue by Akiranya** [divios/DailyShop#164]
**Is your feature request related to a problem? Please describe.**
Just an great enchancement!

**Describe the solution you'd like**
Now the command `/ds sell gui` checks if the items are saleable from ALL shops. I would like to have the command `/ds sell gui` support a [shopName] argument so that it opens a sell GUI but the player can only sell items that the shop `[shopName]` accepts.

**Describe alternatives you've considered**
There is no alternatives ...

**Additional context**

**Comment by divios** [comment]
Hi! Nice catch, I will implement this on the next update

**Comment by Akiranya** [comment]
Hey divios! I just had a great extra idea to this feature! If possibile, could you make it support `/ds sell gui [shopName] [playerName]` so that it can be executed from the console to open a shop sell GUI for the player.

I am making a RPG style server and the players are required to sell items via a NPC in the main city. With this feature, I can simply forbid the player using this command (so the players cant just sell items at their home), and let console execute the command for the player.

**Comment by Akiranya** [comment]
Any updates on this issue? ...
