### ISSUE TITLE
Messages about shop restock

### ISSUE THREAD

**Issue by TheMalasti** [divios/DailyShop#165]
I have 5 different shops that updated every 4 hours, it spamms in chat 5 times that shops were restocked

Possibility to turn it off or to make them in one message

**Comment by divios** [comment]
Hi! You can already do this, check the details [here](https://github.com/divios/DailyShop/wiki/Disable-Restock-Message). I recommend to first read the wiki in detail in case the feature is already implement and to better understand the plugin
