### ISSUE TITLE
Random Items

### ISSUE THREAD

**Issue by goldenkuky209** [divios/DailyShop#168]
Hello, I have a question about DailyShop before buying it. Does the plugin have "Daily" shops or "Changing" shops?
I mean shops that change items every day automatically.

**Comment by Chlachta** [comment]
![image](https://user-images.githubusercontent.com/104257184/183279025-dd36d868-ee3e-4806-8536-9eca5b436b38.png)
Yeah, in file you set all the f.e. blocks you want, you set in seconds how often will change and after that time, shop will change blocks

**Comment by divios** [comment]
> ![image](https://user-images.githubusercontent.com/104257184/183279025-dd36d868-ee3e-4806-8536-9eca5b436b38.png) Yeah, in file you set all the f.e. blocks you want, you set in seconds how often will change and after that time, shop will change blocks

Thanks for replying it!
