### ISSUE TITLE
(very important) When update to Daily Shop 3.4.8 old item in shop dead

### ISSUE THREAD

**Issue by l3unnyAnoF4** [divios/DailyShop#19]
### right click not working

https://user-images.githubusercontent.com/67956962/132998564-f16da3af-ef1b-48d6-9ce0-5c6b8ee915e8.mp4

**Comment by l3unnyAnoF4** [comment]
3.4.7 it work

**Comment by divios** [comment]
Hi! That should only happend when the item sell price is set to -1, did you check that?

**Comment by divios** [comment]
If you checked that and that is not the issue, please send me your .db so i can check it

**Comment by l3unnyAnoF4** [comment]
Use 3.4.8
[dailyshop.zip](https://github.com/divios/DailyShop/files/7150298/dailyshop.zip)

**Comment by divios** [comment]
Is this happening with a lot of items or just this one?

**Comment by l3unnyAnoF4** [comment]
Just this one I think because decimal point

**Comment by divios** [comment]
Yeah could be, if you reStock the shop does this happen again? Is not happening to me right now

**Comment by l3unnyAnoF4** [comment]
Occurs, only items with a selling price of 0.3

**Comment by l3unnyAnoF4** [comment]
can you fix it

**Comment by divios** [comment]
Yeah, I 'll take a look as soon as i can

**Comment by l3unnyAnoF4** [comment]
Close be cuz Daily Shop-3.4.9 Its Work

and
Daily Shop-3.4.9 - Right click Sell Not Work

[Right click Sell Not Work.zip](https://github.com/divios/DailyShop/files/7156267/Right.click.Sell.Not.Work.zip)
