### ISSUE TITLE
When restart server and parser reset?

### ISSUE THREAD

**Issue by l3unnyAnoF4** [divios/DailyShop#21]
bug?

**Comment by divios** [comment]
Hi! I'm not sure what you mean

**Comment by l3unnyAnoF4** [comment]
My store has been reset. But still not sure if it actually resets or not. let me test first again

**Comment by l3unnyAnoF4** [comment]
/dshop manager
![image](https://user-images.githubusercontent.com/67956962/133125000-08393ac6-276b-4acb-bb45-e4e7893376b7.png)

/dshop open Survival
![image](https://user-images.githubusercontent.com/67956962/133125029-34fa374f-1a70-4cc0-8e69-9ecfc7628434.png)

Folder parser
![image](https://user-images.githubusercontent.com/67956962/133125081-3501b8a9-6349-4db8-bb19-01f8044064a2.png)

**Comment by divios** [comment]
When does this happend?

**Comment by l3unnyAnoF4** [comment]
remove dailyshop.db and drop file Survival.yml to Folder parser and use /dshop parser parser Survival

**Comment by divios** [comment]
Is there any errors on console? And could you send me your Survival.yml?

**Comment by l3unnyAnoF4** [comment]
[Survival.zip](https://github.com/divios/DailyShop/files/7156114/Survival.zip)

**Comment by divios** [comment]
I'm testing it right now and is parsing all the items correctly. What do you mean exactly by your shop has been reset? If you mean the timer then yes, every time you parse items the shop is restocked

**Comment by l3unnyAnoF4** [comment]
i don't see any item in /dshop manager

**Comment by divios** [comment]
Thats really weird... is parsing all the items correctly in my test server... Can you send me a video reproducing the exact steps you took? Also here you have your .db parsing the items correctly 
[dailyshop.zip](https://github.com/divios/DailyShop/files/7156160/dailyshop.zip)

**Comment by l3unnyAnoF4** [comment]
https://streamable.com/feog60

**Comment by divios** [comment]
You are incredible right, thnaks for reporting this, i'll update the fix ASAP

**Comment by l3unnyAnoF4** [comment]
I'm always following, it's a great plugin for my server.

**Comment by divios** [comment]
Check the new update, it should fix this issue, let me know if it does just in case
