### ISSUE TITLE
[Question] about features in DailyShop Premium

### ISSUE THREAD

**Issue by ArtifactyNight** [divios/DailyShop#27]
can i see full features about dailyshop premium please?
i'm so interesting to buy it!

Edit 1:
Also Premium version can change display action item or not?
![image](https://user-images.githubusercontent.com/53427253/133775333-3fca5a32-571c-4e2d-ac96-ce4baf4130ce.png)

**Comment by divios** [comment]
Hi! The current premium features are:
- Log System
- MultiCurrency support
- Yaml support
- Individual stock
- Bundles
- Multiple Shops

And finally no, you cannot edit the display action item

**Comment by ArtifactyNight** [comment]
okay!
in the future, do you have plan to make it can custom display action item or not? btw

**Comment by divios** [comment]
Mmm no, is very unlikely. Althought if i implement it will be available in both free and premium versions
