### ISSUE TITLE
disable debug on console when sell item 

### ISSUE THREAD

**Issue by l3unnyAnoF4** [divios/DailyShop#31]
![image](https://user-images.githubusercontent.com/67956962/134233700-839fea84-e4b2-4c74-9eaf-48ecc86edb09.png)
![image](https://user-images.githubusercontent.com/67956962/134233722-f35c8f91-10a8-4b90-a7de-c2c839997163.png)

**Comment by l3unnyAnoF4** [comment]
3.5.2v1 Bug duplication glitch? Did you fix it in version? 3.5.2v2

**Comment by divios** [comment]
Hi! Yeah it is fixed in v2, sorry about that, i forgot to delete the debug message
