### ISSUE TITLE
Limit Sell feature

### ISSUE THREAD

**Issue by ArtifactyNight** [divios/DailyShop#33]
Allow admin can set limit amount item which player can sell item until restock (Global /  Individual)

**Comment by divios** [comment]
mmm you mean a stock for selling items right?

**Comment by ArtifactyNight** [comment]
yes!

**Comment by NekrosBurek** [comment]
Is this still not implemented? And also if possible to add not global stock but per player (Like player can purchase max x stacks on one cycle/restock and also for sell option
Because it can save server from abusing a bug or creating massive farms

**Comment by divios** [comment]
Hi! Sadly it still not implemented for the moment, I’ve been focused on other things. 

For the global stock, you mean that the global stock should have a limit per player?

**Comment by divios** [comment]
This have been now moved to #90
