### ISSUE TITLE
Geyser not work with Daily Shop Premium 3.5.3

### ISSUE THREAD

**Issue by l3unnyAnoF4** [divios/DailyShop#34]
Previous version

https://user-images.githubusercontent.com/67956962/134786583-c8839784-5d06-4cfa-9a3f-404781a4199f.mp4

Current version

https://user-images.githubusercontent.com/67956962/134786550-22d83613-72e7-485b-ba42-fb3714230b4e.mp4

**Comment by divios** [comment]
mmm i am pretty sure this is geyser's fault since it is a little buggy specially with inventories, or at least since the last time i used geyser there was a lot of plugins that were not working properly
