### ISSUE TITLE
CRITICAL! Dupe money

### ISSUE THREAD

**Issue by ArtifactyNight** [divios/DailyShop#35]
Player can sell item more than himself

How to do:
1. Give diamond 40 ea
2. Spam sell MAX button
3. Click Yes

Player can sell diamond without losing the diamond

**Comment by l3unnyAnoF4** [comment]
What version

**Comment by divios** [comment]
Hi! In what version are you in? Also free or premium? I am trying to replicate this and is not happening on my test server with the last premium version

**Comment by divios** [comment]
Alright that was not the issue, for some reason a check wasn't properly initialized and if a player adds items without buying them and leaves the server they mantain those items

**Comment by ArtifactyNight** [comment]
I'm testing with Premium version `3.5.3`
He can make money from 10K to 190K with 40 diamond (I set diamond price is 600 per each)
so i'm very sure this is can dupe

And he share a screen in discord and show how to do it

**Comment by divios** [comment]
mmm weird, i spammed max button too and it is working fine and the code looks fine too, i'm not really sure how is he doing. Could you send me a video?

**Comment by ArtifactyNight** [comment]
for some reason sometime it's work and not work
He testing with spam max button and cancel and spam again and click yes and loop it

.. maybe it's because 3rd party plugin?

Chestsort plugin?
https://www.spigotmc.org/resources/chestsort-api.59773/

**Comment by divios** [comment]
Let me try it with that plugin

**Comment by ArtifactyNight** [comment]
oh nvm it's not max button but it's add button 
sorry about that

here is a videos
https://streamable.com/x6puet

**Comment by divios** [comment]
What is your minecraft server's version?

**Comment by ArtifactyNight** [comment]
purpur 1.17.1 1394

**Comment by l3unnyAnoF4** [comment]
I think he use version 3.5.2v1

**Comment by divios** [comment]
can you send me your .db file? I want to check it manually

**Comment by ArtifactyNight** [comment]
... I sincerely apologize  
i'm using Premium `3.5.2`
now i'm tested with Premium `3.5.3v3`

it's have no issues now
my bad 😭

**Comment by l3unnyAnoF4** [comment]
> I think he use version 3.5.2v1

I told you

**Comment by l3unnyAnoF4** [comment]
I can do this in version 3.5.2v1.

https://streamable.com/riy7vq

**Comment by ArtifactyNight** [comment]
;-; i'm so sorry

**Comment by divios** [comment]
No problem, thanks both for reporting the issues :D
