### ISSUE TITLE
Trying to buy items + creating items

### ISSUE THREAD

**Issue by Fantom250YT** [divios/DailyShop#45]
Not sure if I’m doing something wrong though when I select on one of the daily items and select yes it just goes back to the main menu doesn't allow me to choose how much / even get the item.
This might just be a me issue it's just a bit weird.

Another issue I'm having is when I go to create a item I have a oak plank in my hand for example and it just says "Create and item from grass" even when I have no grass in my inventory.

Also what does MAX mean in the menu?

**Comment by divios** [comment]
Hi! The confirm menu sets by default the amount of the item to 0, so if you click right away yes it won't give you anything. I feel like i should put it to 0 by default to avoid misunderstandings.

The other menu has two options,  the first is to create an item from scratch, this is by default grass, and the other option is to configure an item from your inventory, just click on that option and then click in the air with the item you want to choose equipped in your hand

**Comment by Fantom250YT** [comment]
Ah ok, how do I add more of the item?

**Comment by divios** [comment]
There should be green panes to add items. Also if you don't have enought money or enought space those panes won't appear

**Comment by Fantom250YT** [comment]
AH I see I didn't have enough space!
Thanks for your help!
