### ISSUE TITLE
Very big bug

### ISSUE THREAD

**Issue by mani1232** [divios/DailyShop#46]

**Comment by mani1232** [comment]
If I choose stock 64 then when the player buys something then 64 is the amount of the item * 2 or 3

**Comment by mani1232** [comment]
There is a chance when opening a store to take items without buying them

**Comment by mani1232** [comment]
How to make a stock to buy or sell separately?

**Comment by mani1232** [comment]
![image](https://user-images.githubusercontent.com/70480001/142079702-31f79fc0-6733-493e-b45a-9dd9762b26f6.png)

**Comment by mani1232** [comment]
3.5,7 plugin versiion
1.17.1 purpur latest

**Comment by divios** [comment]
Hi! This should be fixed on the new update
