### ISSUE TITLE
NEW FUNCTIONs (idias)

### ISSUE THREAD

**Issue by yellow-pillow** [divios/DailyShop#48]
1) Hi, could you please add a change button function for buying and selling?

now the left mouse button to buy and the right button to sell

make the change in the settings))

For example, in the config:
change_sell_buy_button: true

2) to make the price will be reduced with each sale of the player item?

I have a server server is built on the pursuit of first place in the balance and I do not want people to sell the same thing all the time, can the plugin do it?

I propose to make lines:

reduce the price when selling: true
reduce the price by how much: 1
increase the price when buying: true
how many percent to increase the price: 1
(make it possible not to use integers)

**Comment by yellow-pillow** [comment]
It would be nice if the premium version had a separate storage of stores, not in the database 

+ make it possible to clean the database (so that it does not clutter up the disk space
(I am still setting up a plugin, perhaps the database will not take up space at all)

**Comment by divios** [comment]
> 1. Hi, could you please add a change button function for buying and selling?
> 
> now the left mouse button to buy and the right button to sell
> 
> make the change in the settings))
> 
> For example, in the config: change_sell_buy_button: true
> 
> 2. to make the price will be reduced with each sale of the player item?
> 
> I have a server server is built on the pursuit of first place in the balance and I do not want people to sell the same thing all the time, can the plugin do it?
> 
> I propose to make lines:
> 
> reduce the price when selling: true reduce the price by how much: 1 increase the price when buying: true how many percent to increase the price: 1 (make it possible not to use integers)

1. Fair enough, I’ll add that option to the TODO list
2. This is a planned feature but it will take some time to be implemented I’m afraid

**Comment by divios** [comment]
> It would be nice if the premium version had a separate storage of stores, not in the database
> 
> * make it possible to clean the database (so that it does not clutter up the disk space
>   (I am still setting up a plugin, perhaps the database will not take up space at all)

I’m not sure what you mean, are you asking for more methods to storage the items, like MySQL or mongoDB?

**Comment by yellow-pillow** [comment]
+ I want to be able to store files in yml and transfer them to other servers

+ Also, please make it possible to display only flat prices, without fractions (with a random price every day)
prices without fractions: true

**Comment by divios** [comment]
1. This is also a planned feature, to make a backup of the shop and also be able to import shops on other servers, but for now they only way to do this is copy and paster the .db file or messing with the .db file which I don't recommend.
2. You mean decimals? For example (3.300 to 3.3)

**Comment by yellow-pillow** [comment]
2. Yes, I think decimal fractions in prices are inconvenient and useless, maybe someone needs them, so I do not propose to abandon it completely, but just suggest to make a function to disable them

+ I'm redesigning stores right now, and I think this feature would be convenient for launching all stores
![image](https://user-images.githubusercontent.com/90108493/142876250-23897828-2aa0-4354-8288-a15231263e26.png)
