### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yellow-pillow** [divios/DailyShop#49]
Hi, I don't understand how the RUN_CMD action works
![image](https://user-images.githubusercontent.com/90108493/142815848-832ae193-87e5-49f0-8260-1bcfc258ce93.png)

but even if I did something wrong, you should definitely add how it works to wikipedia:
![image](https://user-images.githubusercontent.com/90108493/142816217-19d3fa42-03b7-48b2-a0ee-20c0f80121eb.png)

As for the details, I want it to work menu command and I would be sent to the main menu of the server made through chest commands

**Comment by divios** [comment]
Hi! You are right, I have to update the wiki. As for how it works, it just runs the command you put there when the item is clicked, so you could achieve want you want with RUN-CMD:(chest command to run). Also it supports %player% placeholder that will be replaced with the player name who clicked the item

**Comment by yellow-pillow** [comment]
RUN-CMD:(chest command to run)

The point is that the command to open my menu /menu
![image](https://user-images.githubusercontent.com/90108493/142868093-2208836b-73cc-4843-bb92-4a68f0d46724.png)

**Comment by divios** [comment]
just put then RUN_CMD:menu

**Comment by divios** [comment]
Well thinking it twice, you should put RUN_CMD:menu %player%

**Comment by yellow-pillow** [comment]
I get it, the commands come from the console, this is an important clarification and now everything makes sense))

just usually in plugins commands are executed on behalf of the player, and for console commands do CONSOLE

**Comment by divios** [comment]
Yeah, I think I have to clarify this on the wiki, sorry about that
