### ISSUE TITLE
sell confirm

### ISSUE THREAD

**Issue by yellow-pillow** [divios/DailyShop#50]
![image](https://user-images.githubusercontent.com/90108493/143005774-e3157d8e-1536-40cb-8e43-da4c45c360b9.png)
For me, this menu is absolutely useless and unnecessary
It just gets in the way.

maybe replace it with this one with this one with this one with this one?
 (yes, I figured out that 2 menus open only if the product in a single quantity, but what's the point? it does not affect anything)
![image](https://user-images.githubusercontent.com/90108493/143006445-902c1114-c18d-41c0-8c25-c0b9753ded8a.png)

+ urgently need this feature, without it I can not plugin on the server as it is just wildly not convenient

**Comment by yellow-pillow** [comment]
I suggest that we make four choices here:
true/false/confirmation/other_number
![image](https://user-images.githubusercontent.com/90108493/143011032-abbfb69f-831a-4733-95e8-2d7e5530c173.png)

**Comment by divios** [comment]
I am not sure why it is highly inconvenient for you, that menu was designed to confirm the purchase of an item and it does that function correctly, in case you don't want to it just disable the confirm_gui option.

Maybe if you could show me an example of what you are trying to achieve I could understand you better

**Comment by yellow-pillow** [comment]
Hi, you see you have two kinds of confirm gui

and when there are 10 products in the store, the confirm gui is not convenient
![image](https://user-images.githubusercontent.com/90108493/143238516-85885fb2-0bd7-4bab-b704-95bdab43ec5f.png)


and when the product is 1 it displays a convenient confirmation of sale, where you can add the amount sold, right?

i want to always show confirm gui where you can add items, you know? so when you click on any item you can sell the entire inventory of goods, (this menu opens only if you select 1 item in the store, and if you select a number of 10, the menu from 1 example appears)
![image](https://user-images.githubusercontent.com/90108493/143238596-6d89e984-0617-4873-b7a5-55588fc17c17.png)


instead of having to click 100 times to sell like i did in the 1st example

**Comment by yellow-pillow** [comment]
Maybe I don't understand something and you can tell me

**Comment by divios** [comment]
To achieve what you are trying to do, just delete the "set" option. This option "lock" a certain quantity of an item for a fixed price, leading to the confirm Gui since the quantity of the item shouldn't be touched. Just delete that option and recalculate the item price for your needs and then you are good to go

**Comment by yellow-pillow** [comment]
Man, in shop gui + was made very convenient, I thought it could be the same here)

**Comment by yellow-pillow** [comment]
can you make this part look like shop gui+?

It's just that when you offer unit prices the prices look ridiculous, they are too small :(((

**Comment by divios** [comment]
I thought about it and yeah, I think I will try and change it, maybe just us shopGui+ or with some modifications
