### ISSUE TITLE
Disable selling

### ISSUE THREAD

**Issue by byXToGo** [divios/DailyShop#51]
I'd love to see an option to disable selling for items. Would be very useful for shops where you should only be able to buy items (which would actually be every single shop on our server). An option to disable buying would probably also be useful for some people

**Comment by yellow-pillow** [comment]
Put a price of -1 in the buy or sell section and that way you will cancel this option

**Comment by divios** [comment]
As yellow-pillow said, you can achieve this by setting the price to -1
