### ISSUE TITLE
bug on the sale of all inventory

### ISSUE THREAD

**Issue by yellow-pillow** [divios/DailyShop#52]
when players try to sell their entire inventory or even more (by picking up items at the same time) the plugin thinks that they do not have these items and gives an error + items sometimes disappear, but you can return them

HOWEVER, not everyone knows how to get them back so this error is very confusing!

how to fix it? - easily! I know at least 1 way and that is to make the button sell all functional, what would it immediately sold items (and not just threw them on the clipboard)

Also, you can make things stay in your inventory when they go to the clipboard, this will also fix possible bugs in the future, although it will not be very nice

But if you think of another way to fix it, it would be cool! 

however make the sell all button functional and make it sell the items immediately it would be very good too ))

+ i have video
https://drive.google.com/file/d/1ws2avCIJaW9TLosJUDKW3O5tMCtpJzq8/view?usp=sharing

**Comment by divios** [comment]
Thanks for spotting this, I’ll fix it ass soon as I can taking into account the things you said

**Comment by divios** [comment]
I updated the plugin just now but it doesn't fix this issue, the next update will take care of it. 

Also the new update allows /ds restock --all as you requested and the set feature as shopGui+

**Comment by yellow-pillow** [comment]
Yes, I downloaded the update, but the bug is not fixed((

**Comment by divios** [comment]
Are you in 1.18?

**Comment by divios** [comment]
I want to know so i can send you a jar that fix this (only tested it on 1.18)

**Comment by yellow-pillow** [comment]
I recorded the video from version 1.16.5

the server is also on version 1.16.5

**Comment by divios** [comment]
[This build](https://we.tl/t-HyylwMqu1k) should fix this issue, it now uses packets to make it seem as if the item was taking from the player's inventor but, in reality, it is still there. This is a way safer method to handle the confirm menus but, sadly, the limitation is that players cannot take more items if their inventory is full
