### ISSUE TITLE
1.18 update

### ISSUE THREAD

**Issue by chiayiiiii** [divios/DailyShop#53]
As Minecraft and Spigot 1.18 has been released, would be really grateful if you could update the plugin to support the latest versions!

**Comment by divios** [comment]
Hi! I’m waiting for some key dependencies to be updated, as soon as they are available I’ll update the plug-in to the new version

**Comment by mani1232** [comment]
Vault + CMI, working on 1.18

**Comment by divios** [comment]
The key dependency is NBTApi, which dailyShop heavily relays on and still not updated to 1.18,sadly

**Comment by chiayiiiii** [comment]
Thanks Gotcha. I asked the dev for NBT API, and he says there is already a snapshot version 2.9.0-SNAPSHOT, which can be shaded by changing the version number. He says he should update to official release very soon.

**Comment by divios** [comment]
You were right, thanks for notify me! I didn't realize there was a SNAPSHOT version, the premium version is now updated, in a few minutes I'll update the free version too
