### ISSUE TITLE
Console Error While importing a Shop From shopgui+ and the automatic restock Not working anymore

### ISSUE THREAD

**Issue by SNokerYT** [divios/DailyShop#55]
Console Error While importing a Shop From shopgui+ the automatic restock stop working after this error i had to restart the server but the problem is that Even after restarting the problem still there the automatic restock not working anymore
https://paste.md-5.net/gudifexiju.md

**Comment by SNokerYT** [comment]
![image](https://user-images.githubusercontent.com/68678154/145669081-3ec34454-7ee1-4020-8212-ae7ebf0345d7.png)

**Comment by divios** [comment]
Fixed with new update
