### ISSUE TITLE
Stock Count not showing in shop

### ISSUE THREAD

**Issue by ExEndV2** [divios/DailyShop#56]
Hello, the plugin is good, I only have 1 problem about stock. I just want the stock count to be shown in the shop. I used default lang.yml and didn't edit any lines in config.yml.
Plugin Information:
![image](https://user-images.githubusercontent.com/19740277/145687843-dbe61f64-ceb5-48f0-bfad-52ad8c528bd8.png)

Video:
https://imgur.com/AElxDJ5

**Comment by divios** [comment]
Hi! Is this with the new version 2.6.0?

**Comment by divios** [comment]
I just found the bug, I will update the fix tomorrow
