### ISSUE TITLE
New features.

### ISSUE THREAD

**Issue by Aides123** [divios/DailyShop#57]
Hey!
I suggest adding commands for quick sales such as:
- /sellall < Sells all inventory items.
- /sell hand < Sell an item from your hand
- /sellgui <- Opens a GUI where you upload items and sell after closing

**Comment by divios** [comment]
Nice ideas! I will implement them on the next updates

**Comment by Aides123** [comment]
With extended use, I have one more suggestion.
That the item added by the command should have the same amount that we keep. For example i have 64x dirt and i want to put it in my store, but after entering command and adding it there is only one block.

**Comment by Aides123** [comment]
Two more suggestions:
- Sorting. Items that are added via a command should be immediately arranged as you place them. 
- New page. Option that will allow you to add another page for your shop.

**Comment by Aides123** [comment]
Also adding a SLOT option for a selected item that is in the store to buy/sell

**Comment by divios** [comment]
> With extended use, I have one more suggestion. That the item added by the command should have the same amount that we keep. For example i have 64x dirt and i want to put it in my store, but after entering command and adding it there is only one block.

yeah i think that make more sense, I will change that

> Two more suggestions:
> 
>     * Sorting. Items that are added via a command should be immediately arranged as you place them.
> 
>     * New page. Option that will allow you to add another page for your shop.

The first is true, it can be a nice QoL change. And the page option is a nice idea too, i didn't think that before... but it may take some time to be implemented since I have other priorities now

**Comment by divios** [comment]
> Also adding a SLOT option for a selected item that is in the store to buy/sell

I'm not sure what do you mean with this, could you add an example?

**Comment by Aides123** [comment]
> 
![image](https://user-images.githubusercontent.com/23367220/145892759-6bc0d1c1-1f3b-44b9-a5c2-4142c5515420.png)

**Comment by divios** [comment]
You mean that the item should be “static” in the shop and always available?

**Comment by Aides123** [comment]
> You mean that the item should be “static” in the shop and always available?

Yes - Static, always available and in the designated slot in the GUI

**Comment by divios** [comment]
Hi! The new update adds the sorting and keeps the same amount when adding an item. I still have to implement the commands you suggested and also the option to add pages. About the static slot, I am still thinking how to implement but it may take some time

**Comment by Aides123** [comment]
> Hi! The new update adds the sorting and keeps the same amount when adding an item. I still have to implement the commands

Cool, do you know approximately when you will be able to add a static slot?

**Comment by divios** [comment]
I cannot be certain, and I usually don’t like to give an extimated time but expect in the following days

**Comment by Aides123** [comment]
> I cannot be certain, and I usually don’t like to give an extimated time but expect in the following days

Hey, and what does this look like?
Will this be added this month? I'm finishing making a server and don't know whether to wait for this plugin or use another one xD

**Comment by divios** [comment]
Hello! That is why I do not like to give an estimated time D:, some errors arose and I have been focused on solving them during these past weeks, now I have exams, so I am afraid that I cannot implement new things until after the 19th of this month.

**Comment by Aides123** [comment]
> Hello! That is why I do not like to give an estimated time D:, some errors arose and I have been focused on solving them during these past weeks, now I have exams, so I am afraid that I cannot implement new things until after the 19th of this month.

Ok thank you ^^

**Comment by Aides123** [comment]
And I propose to create a public TODO where you write down accepted proposals to see what is planned to add

**Comment by divios** [comment]
Hi! This finally was implemented, [this](https://we.tl/t-16FMMa6QPZ) is the development build that adds it, you just need to add the field `static: slot`, where slot is the position on the inventory you want the item to appear. This slot has to be empty, and also you need to restock the shop

**Comment by divios** [comment]
The new update finally adds the sell commands feature
