### ISSUE TITLE
Doesn't work correct

### ISSUE THREAD

**Issue by BlazeLX** [divios/DailyShop#58]
This is my config

items:
  13f6e026-94a9-4c00-b929-21c90a669dfd:
    material: DIAMOND
    quantity: 32
    buyPrice:
      min: '5.0'
      max: '15.0'
    sellPrice:
      fixed: '1.0'
    rarity: Rare
    econ:
      name: playerPoints
    confirm_gui: true
    nbt:
      Damage: 0

Is it a bug (on the screen) that i can buy 32 diamonds and 2 diamonds for one price? And also i can buy overlimit shop items by clicking on the button "max" (on the screen)

![Screenshot_2](https://user-images.githubusercontent.com/95657429/145892357-46cb99cc-46d3-4852-bf8f-13e9e60c4a85.png)

**Comment by divios** [comment]
Hi! Is this with the premium or the free version?

**Comment by BlazeLX** [comment]
In vault too. I set 32 amount of emerald, but can sell 1 item for price of 32

**Comment by divios** [comment]
Could you send me a video?

**Comment by BlazeLX** [comment]
![разрабу](https://user-images.githubusercontent.com/95657429/145896920-ae76881d-9bc2-4c7d-95aa-7616ff2c864e.png)
check it pls (step by step to reproduce my problem) (i dont have enough time to make video, sry)

**Comment by BlazeLX** [comment]
1-5 steps works correct. but if i set 2+ items (6-8 steps), it doesn't (mc 1.17.1)
I can sell more that needed and don't give correct price if items in not a 32

**Comment by divios** [comment]
Okay, I finally understand the bug, thanks for reporting it, I will update the fix tomorrow

**Comment by BlazeLX** [comment]
ty so much <3

**Comment by divios** [comment]
I decided to update the plugin now since it was an important bug, thanks for reporting it again!

**Comment by BlazeLX** [comment]
WOW! It's unbelieveble...You are first author, who made it so fast...My founded bugs in other plugin not fixed for more than 2 week...Thank you so much :)
