### ISSUE TITLE
Permission doesnt work

### ISSUE THREAD

**Issue by Aides123** [divios/DailyShop#61]
Hey! I'm trying to give access to the store, but after granting it, it still says there is no permissions.
from INNE.YML
id: INNE

![image](https://user-images.githubusercontent.com/23367220/146654942-63fc23ce-0d35-4885-82f8-0152943ed19b.png)

**Comment by divios** [comment]
Sorry about that, is dailyrandomShop instead of dailyShop, I edited the wiki and I still have to update the plug-ins with the changes

**Comment by Aides123** [comment]
Thanks :3

I still have a question, is it possible to disable giving items to inventory before buying them? Currently the item is assigned to the inventory when I try to buy it, and it interferes with some of my item limit plugins :p

**Comment by divios** [comment]
Im afraid is not possible at the moment, is a little hardcoded, I may add an option in the future to prevent this but I can't promise anything
