### ISSUE TITLE
Can't add items to shops + error

### ISSUE THREAD

**Issue by Geekmakes** [divios/DailyShop#62]
I'm probably doing something wrong but I haven't been able to add any items to the shops. All I get is a error in console.

Using Latest Purpur and vault.

https://pastebin.com/JHu0AzqC

Thank you!

**Comment by divios** [comment]
Not at all, this a weird error that should be patched on the newest update, thanks for reporting it!

**Comment by Geekmakes** [comment]
Newest update broke it more unfortunately

**Comment by Geekmakes** [comment]
![2021-12-29_21 18 48](https://user-images.githubusercontent.com/16181272/147716646-fc5fe87d-cfcd-4b02-bbb4-6524f3c61d45.png)
This is all I'm getting in game

And in console:
https://pastebin.com/y7ZuF6bu
