### ISSUE TITLE
Troubles with clean v1.6.3 install

### ISSUE THREAD

**Issue by MaxIsV** [divios/DailyShop#63]
Hello, after upgrading to v1.6.3 I got a weird error in the console. I decided to try deleting the plugin folder and reinstalling it, and I also got this error: https://pastebin.com/B5DEpeL3

In the game, I can only open the "potion" shop, but even there no products are displayed.

My server: purpur-1.17.1-hotfix3

**Comment by divios** [comment]
Hi! This was a mistake a made checking some arguments, the new update fix this. Thanks for reporting it thought
