### ISSUE TITLE
Several suggestions

### ISSUE THREAD

**Issue by MaxIsV** [divios/DailyShop#64]
Hi, I have a few suggestions for this amazing plugin: 

1) Add an ability to make line breaks in "lang.yml" by creation a new line, instead of using "|". I.e. add StringList support. 
I think that when each new line is written on a new line, it is much more convenient and easier to style the necessary text beautifully.

2) Add options inside "lang.yml" to configure names of the rarity degrees. It would be useful for non-english users

3) Add HEX color codes support

**Comment by divios** [comment]
Hi! Great suggestions:

1. I have pending to do a rework of the lang.yml internally and I will try to add this
2. This has been requested before and I have to add support for it too.
3. Again, this has been requested before hehe, I also have it in the todo list

There a lot of changes I have in mind but this suggestion will be implemented in the following days or in the next weak

**Comment by MaxIsV** [comment]
> Hi! Great suggestions:
> 
> 1. I have pending to do a rework of the lang.yml internally and I will try to add this
> 2. This has been requested before and I have to add support for it too.
> 3. Again, this has been requested before hehe, I also have it in the todo list
> 
> There a lot of changes I have in mind but this suggestion will be implemented in the following days or in the next weak

I also want to ask why there is still a "Set" feature in the item editor, although v3.6.0 changelog says it was replaced by "Quaintity"?

**Comment by divios** [comment]
True, I have to update the "set" to quantity. Also what do you mean by you can't a se tup a stock for a product? If you are asking in the gui, you need to first _enable_ the stock, and then left click again and you can set the quantity

**Comment by MaxIsV** [comment]
> True, I have to update the "set" to quantity. Also what do you mean by you can't a se tup a stock for a product? If you are asking in the gui, you need to first _enable_ the stock, and then left click again and you can set the quantity

I mean, when the quantity of a product is 1, then I can set stock to it and see this:
![2021-12-26_13 56 13](https://user-images.githubusercontent.com/58142896/147407373-8aac0a1e-b4bf-4cb1-92c4-46919e64ee20.png)

But when product quanity is > 1, for example 8, I only see "**UNAVAILABLE**":
![2021-12-26_13 56 21](https://user-images.githubusercontent.com/58142896/147407396-a9284d1a-c0e1-474b-94d0-cc02f45818d1.png)

**Comment by divios** [comment]
Oh okay, yeah you cannot set quantity and stock at the same time, they can cause some unwanted behaviour. To set the stock quantity, instead, enable the stock and then left click again.

**Comment by divios** [comment]
The new update adds hex support :D
