### ISSUE TITLE
too many bugs

### ISSUE THREAD

**Issue by yellow-pillow** [divios/DailyShop#66]
you made some huge mistake in the plugin and now it can be said to not work at all 

I upgraded from the old version and now the displayed prices don't change and only the real prices change and it turns out that the store just cheats with the price...

log stopped working, prices are frozen in one place

**Comment by yellow-pillow** [comment]
+ WHAT??

https://drive.google.com/file/d/1F7bvfL-dXujsZEna1umbPQ1e1pgKGHHy/view?usp=sharing

**Comment by divios** [comment]
> you made some huge mistake in the plugin and now it can be said to not work at all
> 
> I upgraded from the old version and now the displayed prices don't change and only the real prices change and it turns out that the store just cheats with the price...
> 
> log stopped working, prices are frozen in one place

the new update should fix this, sorry for that

**Comment by divios** [comment]
> * WHAT??
> 
> 
> https://drive.google.com/file/d/1F7bvfL-dXujsZEna1umbPQ1e1pgKGHHy/view?usp=sharing

This is happening because a priceModifier is applied to you, probably beacause you are op, but for the other players the price is showed correctly. Also the difference in prices from the shop gui and the confirm menu was a bug that was fixed too

**Comment by yellow-pillow** [comment]
I have a funny thing that my store is called a sly miser and the players just started laughing at the fact that he is sly, cheats them with the prices, etc.)

I'll check the fixed bugs tomorrow!

**Comment by yellow-pillow** [comment]
question how often the information is saved in the shops folder?

**Comment by yellow-pillow** [comment]
players have lost the ability to use the command /rdshop open ... 

(I did not change anything in the rights settings, now you can open the store only if the opped player will write the command /rdshop open menu player

if on purpose then why?

if accidentally, then waiting for fixes

spent 20 minutes to figure out what's going on and understand what the bug

**Comment by divios** [comment]
> question how often the information is saved in the shops folder?

only when something is changed via in-game gui

**Comment by divios** [comment]
> players have lost the ability to use the command /rdshop open ...
> 
> (I did not change anything in the rights settings, now you can open the store only if the opped player will write the command /rdshop open menu player
> 
> if on purpose then why?
> 
> if accidentally, then waiting for fixes
> 
> spent 20 minutes to figure out what's going on and understand what the bug

my bad, i will update the fix ASAP

**Comment by divios** [comment]
fixed on the new update

**Comment by yellow-pillow** [comment]
Great, I love it, but what about the bug with the sale of all inventory, it is still relevant((

**Comment by yellow-pillow** [comment]
+ found a bug that the command /rdshop open menu player does not work if the man made himself a fake nick through essentials :((

**Comment by yellow-pillow** [comment]
> fixed on the new update

uncorrected((. in 3.6.4.2
