### ISSUE TITLE
players cant open shop

### ISSUE THREAD

**Issue by yellow-pillow** [divios/DailyShop#69]
Hey bro, happy new year, I'm tired of downloading updates...

You know the error, players still CANNOT open the store:(

You check for updates before downloading them?

seriously... I am very upset ...

**Comment by divios** [comment]
Hi! I'm really sorry for all this mess up, I changed some Internet libraries and it resulted on bugs, but with the new update players should be able to open shops correctly, is version 3.6.4.4?

**Comment by yellow-pillow** [comment]
of course I'm talking about the new version 3.6.4.4

(the problem is still relevant)

if it had everything fixed I wouldn't have said a word

**Comment by divios** [comment]
What permissions does your players have? I just checked and is working fine, the permissions they need is `dailyrandomshop.open` and `dailyrandomshop.open.*`

**Comment by divios** [comment]
PD: I tried to replicate your scenery and yeah, you need to add `dailyrandomshop.open`, with `dailyrandomshop.open.others` only it won't work

**Comment by yellow-pillow** [comment]
Before, it worked only  with   dailyrandomshop.open.menu

**Comment by divios** [comment]
You should need both, if it worked before it must be a bug that now is solved. Again sorry for all the mess D:
