### ISSUE TITLE
Received 8MB worth of console spam after restarting, bricked my server

### ISSUE THREAD

**Issue by layagmc** [divios/DailyShop#70]
I can't start my server without uninstalling DailyShop, sadly - this is a core feature of my server that I will be releasing tomorrow (already posted and spent on marketing materials).

I did not expect a "premium" plugin to be riddled with fatal and too many bugs. 

Can't upload logs on pastebin, and so I am pasting my entire console log in this drive link.

https://drive.google.com/file/d/16UXo-9oJn_XT05eRTu1AZPt1STt0ZcKp/view?usp=sharing

Hoping for a fast response.

**Comment by divios** [comment]
Hi! First I apologize for the bugs. Im working in a new update that should fix most of them. Could you send me your shops files? There seems to be an NBT tag that is causing this but I'm not sure why

**Comment by divios** [comment]
https://mega.nz/file/cnYRHaBI#I_YPrJn55NFT7ju2bSVWEiSVVUVrNEmPV8sofnvMfc4

This should fix that issue

**Comment by layagmc** [comment]
I've tried removing shops one-by-one, it seems like this is the one that's causing the issue.

YAML file changed to .txt for github upload reasons.

I'll try out the dev build

[blackmarket.txt](https://github.com/divios/DailyShop/files/7826034/blackmarket.txt)

**Comment by layagmc** [comment]
![image](https://user-images.githubusercontent.com/96867905/148485660-09f3c7e2-032e-4687-ac21-04261ae874be.png)
Can't seem to remove this item (came from restock). Even if I use the GUI manager.

I am receiving the following console logs:

[03:13:26 WARN]: [DailyShop] There was a problem parsing the item with id 86c8575f-3fb3-4907-b92c-b3df835a90f1
[03:13:26 WARN]: [DailyShop] Unable to parse Malformed Json!
[03:13:26 WARN]: [DailyShop] There was a problem parsing the item with id d28a9184-f20f-4fe0-9e05-f9e76ac02804
[03:13:26 WARN]: [DailyShop] null
[03:13:26 WARN]: [DailyShop] There was a problem parsing the item with id c5698f7b-730a-4092-83dc-6c228a119bbc
[03:13:26 WARN]: [DailyShop] null

**Comment by layagmc** [comment]
ISSUE: The price calculations were disrupted by the dev build. 64 apples that were formerly priced at 2.89 a piece are now priced as a whole stack...

**Comment by divios** [comment]
Sorry mate, I forgot to send you the most recent [build](https://we.tl/t-h1FzoZjNqd), the last I send you have some bugs that this should fix along with what you listed here. Don't forget to delete again the .db file since I think this is what is causing the "Unable to parse Malformed Json".

Also, if the %dailyshop_time_shopname% is still broke (it shouldn't), please check if on load, dailShop puts on console "Hook to PlaceholderApi"

**Comment by divios** [comment]
PD: I forgot to tell you, this new update changes how the price is calculated if the item has a quantity > 1. Now instead of each block = price, now block * amount = price
