### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by yellow-pillow** [divios/DailyShop#75]
all in the video, what you need to repeat: put the mouse on the slot in which to move the item and then click on the number (indicating the slot of the item in htabar) and this item will move to the menu 0_0

https://drive.google.com/file/d/1G-_Vjeb88_FY7v1PeisJDF9CRBG6F9XQ/view?usp=sharing

**Comment by yellow-pillow** [comment]
And it's still relevant, too

https://github.com/divios/DailyShop/issues/52

**Comment by divios** [comment]
> all in the video, what you need to repeat: put the mouse on the slot in which to move the item and then click on the number (indicating the slot of the item in htabar) and this item will move to the menu 0_0
> 
> https://drive.google.com/file/d/1G-_Vjeb88_FY7v1PeisJDF9CRBG6F9XQ/view?usp=sharing

mmm I personally didn't know you could that in minecraft, I will fix on the next update

**Comment by divios** [comment]
> And it's still relevant, too #52

I know, I'm still thinking in a reliable solution

**Comment by divios** [comment]
[This build](https://we.tl/t-Xy97Yc4SFE) should fix this issue, it was a minor bug but thanks for reporting it. This also comes with the fix to #52 and some other minor fixes, try it and let me know if it works
