### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yellow-pillow** [divios/DailyShop#76]
a little bug with the items that got tangled in the wrong menu :(

(the spectral stratum has forgotten its place)

![image](https://user-images.githubusercontent.com/90108493/148846686-8951fe7e-6035-42ad-9d5f-a30491ac362c.png)

![image](https://user-images.githubusercontent.com/90108493/148846722-71fe9c6b-b907-4bf1-8930-1fdd06552d90.png)

**Comment by divios** [comment]
This has been reported before on discord and I'm not sure how that happend, I will investigate it. In the meantime, can you send me your .db file? I want to check something that might point where the error is

**Comment by yellow-pillow** [comment]
No problem, here you go.

https://drive.google.com/file/d/1THoNOZfaAgF6f92XnyQ8MFEs7IsTtu0f/view?usp=sharing

**Comment by divios** [comment]
You are probably going to hate me, but yet again, [another build ](https://we.tl/t-6qHT7gCPvQ) that fix this issue along with your other addressed issues.

**Comment by yellow-pillow** [comment]
hi, everything is great!  the main thing is that the developer fixes the bugs and answers, because many times I have encountered complete ignorance of bugs and you don’t even know what to do, at least hang yourself ;(

**Comment by yellow-pillow** [comment]
and now you fixed all the bugs?  I just remember I suggested some updates, you can add them now


and by the way, I propose to make a discord to help people, github is only known to developers, 2-3 months ago it was torture for me to use it

**Comment by divios** [comment]
All the bugs should be fixed yes, I still have to add some suggestions that were made, I first wanted to first all the bugs.

And yes, you are right, I should open a discord but I have the feeling it will bring unnecessarily anxiety to me, so that’s why I have being delayed it
