### ISSUE TITLE
Price Modifier Suggestion

### ISSUE THREAD

**Issue by ItsSniper** [divios/DailyShop#77]
Hello! I have a suggestion that has to do with shop modifiers. I know that at the moment they are permission based. Would there be any way to make an option for placeholderapi based modifiers too? So if I wanted to give a modifier based on an MMOCore or McMMO level, I could do so? That would be great in my opinion!

Thanks for your time.

**Comment by divios** [comment]
This is a great idea! As soon as I finish my exams I will implement it

**Comment by divios** [comment]
Hi! I know this comes a little late but the new update adds this feature!

**Comment by ItsSniper** [comment]
Thank you! :D
