### ISSUE TITLE
prices after restart

### ISSUE THREAD

**Issue by yellow-pillow** [divios/DailyShop#78]
hello, my prices in stores change after the restart, this is not normal 0_0

**Comment by divios** [comment]
Hi! You mean the random prices between intervals?

**Comment by yellow-pillow** [comment]
Yes, the random prices changed after I turned the server off and back on

**Comment by divios** [comment]
Yes, I'm aware of that bug but thanks for reporting it, I have yet to fix it

**Comment by divios** [comment]
Yet [another fix](https://we.tl/t-MejdMuDK8g), sorry for the spam in all the other threads, but the build fix this issue and the others addressed by you
