### ISSUE TITLE
The plugin is disabled at startup

### ISSUE THREAD

**Issue by GuNanOvO** [divios/DailyShop#79]
Hello, I think you should know the problem.
[DailyShop] Disabled due to: 'net.kyori.adventure.text.minimessage.MiniMessage net.kyori.adventure.text.minimessage.MiniMessage.miniMessage()'

**Comment by divios** [comment]
Hi! Could you send me the entire log? Or is that only the error? Also in what version of Minecraft are you in?

**Comment by GuNanOvO** [comment]
The server version is 1.18.1. This problem occurred when dailyshop was upgraded from version 3.6.3 to version 3.6.6. There are no other logs about dailyshop. Only:
[13:11:49] [Server thread/INFO]: [DailyShop] Enabling DailyShop v3.6.6
[13:11:49] [Server thread/ERROR]: [DailyShop] Disabled due to: 'net.kyori.adventure.text.minimessage.MiniMessage net.kyori.adventure.text.minimessage.MiniMessage.miniMessage()'
[13:11:49] [Server thread/INFO]: [DailyShop] Disabling DailyShop v3.6.6

**Comment by divios** [comment]
Are you using paperMC or spigot?

**Comment by GuNanOvO** [comment]
purpur

**Comment by divios** [comment]
[This one](https://we.tl/t-Y9TEgHPBtj) should fix this issue, please do tell me if it works so I can push an update, it seems that in some versions a dependency is included and I had to shade it so I does not cause conflicts

**Comment by divios** [comment]
I manually check it and it should be fixed
