### ISSUE TITLE
a huge bug

### ISSUE THREAD

**Issue by yellow-pillow** [divios/DailyShop#86]
bro, the latest update is terrible, remove it from everywhere so no one can download it

It took me two days to figure it out. 

I just made a lot of changes and it ended up being about your plugin.
(put an old version and everything worked well again).

in short: you are somewhere very wrong because with every second the load on the processor was growing and growing until it took 6 threads at 100% and my tps was 2 

i'm very upset because i lost a lot of people from advertising :(

**Comment by yellow-pillow** [comment]
Now I have been testing the old version for 2-3 hours and everything is fine, my server is working as before!

old: 3.6.4

**Comment by divios** [comment]
This is a really bug indeed… did you run /timings to check what exactly was causing this?

**Comment by yellow-pillow** [comment]
I can now say for sure that your plugin is to blame, because it's been 20 hours and everything is fine.

**Comment by divios** [comment]
Yes I know, I believe you, I’m just asking if you perhaps run /timings to see what part of my plug-in was causing this

**Comment by divios** [comment]
> I can now say for sure that your plugin is to blame, because it's been 20 hours and everything is fine.
> 
> Yes, I ran the timings, if you need them I'll look for them, I have them somewhere
> 
> but in the timings I found nothing interesting for me (maybe I don't know how to use them)

Yes please, do send it if you found it, it can be extremely useful

**Comment by yellow-pillow** [comment]
Yes, I changed my message (yours wasn't showing up for me)

Here are some of the timings, these are not the worst moments, but they are still the old version of the plugin

https://timings.aikar.co/?id=472f33a756f344c49b27e4f83653a6df

to understand: on the old version my server can handle 60-70 people

**Comment by yellow-pillow** [comment]
I also remembered! when turning off the server on the new version of the plugin, he started spamming this error for 3-4 minutes in crazy amounts!

If I have a day of logs for 2 archives, your plugin created 3 more archives with spamming the same error

[daily.txt](https://github.com/divios/DailyShop/files/7925631/daily.txt)

**Comment by yellow-pillow** [comment]
By the way, I would be very grateful if you could then show me where you are and how you found the error, because I do not understand timings, and the tutorials in English two hours long is impossible for me

**Comment by divios** [comment]
> By the way, I would be very grateful if you could then show me where you are and how you found the error, because I do not understand timings, and the tutorials in English two hours long is impossible for me

Well timings shows what task are taking more time to run, in your case, is loading chunks (which is usually the thing that take most time). DailyShop is pretty much doing fine, the only thing I can see is that the autoComplete can be optimized.

So, seeing this, the only explanation left is that an async task is doing something funny on the background (async task do not appear on timings), which makes sense since the last .txt you sent me points to an async task. 

I will check what is causing this, but thanks to your help is now clear at least were the error is coming from

**Comment by divios** [comment]
Also consider using/learn the plugin spark, is similar to timings but way better

**Comment by divios** [comment]
Dammit, there was a really weird bug that didn't remove the shop menu (every time a player opens a shop, a new menu is created for them) from the task that updates the items placeholders. So every time a player opened a shop, a new gui was added, so probably, after quite some time, the task had to loop through lots of menus and was causing the overhead in your cpu.

[This build](https://we.tl/t-owBwTC4ow6) fix this, sorry for the bug and also thanks for reporting it D:

**Comment by yellow-pillow** [comment]
great, you did great! it's hard to find mistakes, but you did it, thank you!
I was mentioned somewhere 0_0

about spark, I will definitely try it
I don't understand why the dailyshop was lagging the chunks in timings))

**Comment by divios** [comment]
> great, you did great! it's hard to find mistakes, but you did it, thank you! I was mentioned somewhere 0_0
> 
> about spark, I will definitely try it I don't understand why the dailyshop was lagging the chunks in timings))

Noo, dailyshop wasn’t lagging chunks, I said that timings is showing that the task that is taking most of your cpu resources is loading chunks

**Comment by yellow-pillow** [comment]
on the result I can say that the main part of the problem is fixed BUT if you compare the performance of version 3.6.4 and 3.6.8 the old version shows itself several times more productive, that is, some stubbornness still remained

me hard to understand how it works (I'm testing only 2-3 hours)
maybe be able to tell in the future, but now my thoughts above

**Comment by divios** [comment]
Yes you are right, thanks to your timings report I think I know where the bottleneck is, so soon I will update the fix improving the overall performance

**Comment by yellow-pillow** [comment]
Don't you have your own server? Most developers make plugins for themselves and sell them on top of that 

+ testing on their servers

**Comment by divios** [comment]
I used to have a server but not anymore. I test my plugins in a local server, trying to recreate a normal server behavior but I’m limited in that aspect
