### ISSUE TITLE
Sell All Suggestion

### ISSUE THREAD

**Issue by ItsSniper** [divios/DailyShop#87]
I had another suggestion for a smaller feature. I was wondering if it would be possible to add a "Shift+Right Click" to "Sell All" option to the shop GUIs. So if I have items in stocks of 1, they don't either have to spam click or open up the menu and hit max and confirm, they could instead do a real quick shift+click to sell all.

Thanks for checking out my suggestion. Hope you like it :)

**Comment by divios** [comment]
Hi! The new update adds this but not exactly in the way you are asking, players can **/ds sell gui**  and shift+click as a normal chest to sell items
