### ISSUE TITLE
Limit buy/sell

### ISSUE THREAD

**Issue by divios** [divios/DailyShop#90]
As the name suggest, add a limiter to how many items a player can buy/sell.
It would be nice to add different context, like global, per shop, or per item

**Comment by MidnightSugar** [comment]
Have you considered the shopkeeper balance idea I created earlier? This would prevent players from selling too much in a more realistic way. Right now npcs have limited inventory, but unlimited money.

**Comment by divios** [comment]
> Have you considered the shopkeeper balance idea I created earlier? This would prevent players from selling too much in a more realistic way. Right now npcs have limited inventory, but unlimited money.

Hi! Yes, right now I'm working on this and the shopkeepers since is a really cool idea and I have been prolong it for quite some time

**Comment by divios** [comment]
The new update adds this
