### ISSUE TITLE
Lagg

### ISSUE THREAD

**Issue by mani1232** [divios/DailyShop#93]
Core: purpur b1547

When choosing a material for a  product in the store, tps drops to 16
![image](https://user-images.githubusercontent.com/70480001/152561796-be74c706-6909-443e-8fbc-bc210dbd8663.png)

**Comment by mani1232** [comment]
Version 1.18.1

**Comment by divios** [comment]
That should only happen once, that's caused by Bukkit's initialization inner classes, it's usually done at startup, but if not, it'll only happen once.
