### ISSUE TITLE
Add support Citizens

### ISSUE THREAD

**Issue by mani1232** [divios/DailyShop#95]
I understand what I can do via /npc cmd add ds open [shop] {player} but I just wanted to bind the plugin to the npc

**Comment by divios** [comment]
Mmm I'm not sure what you mean by "bind the plugin to npc", to my understanding attacking the command should be enough?

**Comment by mani1232** [comment]
Bind an NPC by its id

**Comment by mani1232** [comment]
Google translator

**Comment by divios** [comment]
But what are the advantages with that approach?

**Comment by mani1232** [comment]
Maybe it will be better, I just suggested, it's optional
